#!/bin/sh

CONFIG_FILE="$HOME/.today.conf"

# Exit on errors
set -e

# Load configuration file (the source/. command will handle
# the error message if configuration file is missing)
# shellcheck source=/dev/null
. "$CONFIG_FILE"

# Create potentially missing directories
mkdir -p "$DIRECTORY"
MONTH_PATH="$DIRECTORY/$MONTH_DIR_NAME"
mkdir -p "$MONTH_PATH"
FILE_PATH="$DIRECTORY/$MONTH_DIR_NAME/$FILE_NAME"

# Create note if is doesn't exist
if [ ! -f "$FILE_PATH" ]; then
  cat <<EOF >"$FILE_PATH"
$TEMPLATE

EOF
fi

# Open [new or existing] note, and
# let the editor handle the exit code
exec "${EDITOR:-vim}" "$FILE_PATH"

